export const SHOP_DATA = [
  {
    title: 'Hats',
    items: [
      {
        id: 1,
        name: 'Brown Brim',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 25,
      },
      {
        id: 2,
        name: 'Blue Beanie',
        imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
        price: 18,
      },
      {
        id: 3,
        name: 'Brown Cowboy',
        imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
        price: 35,
      },
      {
        id: 4,
        name: 'Grey Brim',
        imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
        price: 25,
      },
      {
        id: 5,
        name: 'Green Beanie',
        imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
        price: 18,
      },
      {
        id: 6,
        name: 'Palm Tree Cap',
        imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
        price: 14,
      },
      {
        id: 7,
        name: 'Red Beanie',
        imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
        price: 18,
      },
      {
        id: 8,
        name: 'Wolf Cap',
        imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
        price: 14,
      },
      {
        id: 9,
        name: 'Blue Snapback',
        imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
        price: 16,
      },
    ],
  },
  {
    title: 'Sneakers',
    items: [
      {
        id: 10,
        name: 'Adidas NMD',
        imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
        price: 220,
      },
      {
        id: 11,
        name: 'Adidas Yeezy',
        imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
        price: 280,
      },
      {
        id: 12,
        name: 'Black Converse',
        imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
        price: 110,
      },
      {
        id: 13,
        name: 'Nike White AirForce',
        imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
        price: 160,
      },
      {
        id: 14,
        name: 'Nike Red High Tops',
        imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
        price: 160,
      },
      {
        id: 15,
        name: 'Nike Brown High Tops',
        imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
        price: 160,
      },
      {
        id: 16,
        name: 'Air Jordan Limited',
        imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
        price: 190,
      },
      {
        id: 17,
        name: 'Timberlands',
        imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
        price: 200,
      },
    ],
  },
  {
    id: 3,
    title: 'Jackets',
    items: [
      {
        id: 18,
        name: 'Black Jean Shearling',
        imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
        price: 125,
      },
      {
        id: 19,
        name: 'Blue Jean Jacket',
        imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
        price: 90,
      },
      {
        id: 20,
        name: 'Grey Jean Jacket',
        imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
        price: 90,
      },
      {
        id: 21,
        name: 'Brown Shearling',
        imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
        price: 165,
      },
      {
        id: 22,
        name: 'Tan Trench',
        imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
        price: 185,
      },
    ],
  },
  {
    id: 4,
    title: 'Womens',
    items: [
      {
        id: 23,
        name: 'Blue Tanktop',
        imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
        price: 25,
      },
      {
        id: 24,
        name: 'Floral Blouse',
        imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
        price: 20,
      },
      {
        id: 25,
        name: 'Floral Dress',
        imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
        price: 80,
      },
      {
        id: 26,
        name: 'Red Dots Dress',
        imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
        price: 80,
      },
      {
        id: 27,
        name: 'Striped Sweater',
        imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
        price: 45,
      },
      {
        id: 28,
        name: 'Yellow Track Suit',
        imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
        price: 135,
      },
      {
        id: 29,
        name: 'White Blouse',
        imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
        price: 20,
      },
    ],
  },
  {
    id: 5,
    title: 'Mens',
    items: [
      {
        id: 30,
        name: 'Camo Down Vest',
        imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
        price: 325,
      },
      {
        id: 31,
        name: 'Floral T-shirt',
        imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
        price: 20,
      },
      {
        id: 32,
        name: 'Black & White Longsleeve',
        imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
        price: 25,
      },
      {
        id: 33,
        name: 'Pink T-shirt',
        imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
        price: 25,
      },
      {
        id: 34,
        name: 'Jean Long Sleeve',
        imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
        price: 40,
      },
      {
        id: 35,
        name: 'Burgundy T-shirt',
        imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
        price: 25,
      },
    ],
  },
];

// fetch data from remote database(firebase) instead, don't need this anymore.


export const Product_Data = [
  {
    category: "hats",
    id: 1,
    name: 'Brown Brim',
    title: 'Brown Brim',
    imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
    price: 25,
    desc: 'description of the hat:',
  },
  {
    category: "hats",
    id: 2,
    name: 'Blue Beanie',
    title: 'Blue Beanie',
    imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
    price: 18,
    desc: 'description of the hat:',
  },
  {
    category: "hats",
    id: 3,
    name: 'Brown Cowboy',
    title: 'Brown Cowboy',
    imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
    price: 35,
    desc: 'description of the hat:',
  },
  {
    category: "hats",
    id: 4,
    name: 'Grey Brim',
    title: 'Grey Brim',
    imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
    price: 25,
    desc: 'description of the hat:',
  },
  {
    category: "hats",
    id: 5,
    name: 'Green Beanie',
    title: 'Green Beanie',
    imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
    price: 18,
    desc: 'description of the hat:',
  },
  {
    category: "hats",
    id: 6,
    name: 'Palm Tree Cap',
    title: 'Palm Tree Cap',
    imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
    price: 14,
    desc: 'description of the hat:',
  },
  {
    category: "hats",
    id: 7,
    name: 'Red Beanie',
    title: 'Red Beanie',
    imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
    price: 18,
    desc: 'description of the hat:',
  },
  {
    category: "hats",
    id: 8,
    name: 'Wolf Cap',
    title: 'Wolf Cap',
    imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
    price: 14,
    desc: 'description of the hat:',
  },
  {
    category: "hats",
    id: 9,
    name: 'Blue Snapback',
    title: 'Blue Snapback',
    imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
    price: 16,
    desc: 'description of the hat:',
  },
  {
    category: 'sneakers',
    id: 10,
    name: 'Adidas NMD',
    title: 'Adidas NMD',
    imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
    price: 220,
    desc: 'description of the sneaker:',
  },
  {
    category: 'sneakers',
    id: 11,
    name: 'Adidas Yeezy',
    title: 'Adidas Yeezy',
    imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
    price: 280,
    desc: 'description of the sneaker:',
  },
  {
    category: 'sneakers',
    id: 12,
    name: 'Black Converse',
    title: 'Black Converse',
    imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
    price: 110,
    desc: 'description of the sneaker:',
  },
  {
    category: 'sneakers',
    id: 13,
    name: 'Nike White AirForce',
    title: 'Nike White AirForce',
    imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
    price: 160,
    desc: 'description of the sneaker:',
  },
  {
    category: 'sneakers',
    id: 14,
    name: 'Nike Red High Tops',
    title: 'Nike Red High Tops',
    imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
    price: 160,
    desc: 'description of the sneaker:',
  },
  {
    category: 'sneakers',
    id: 15,
    name: 'Nike Brown High Tops',
    title: 'Nike Brown High Tops',
    imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
    price: 160,
    desc: 'description of the sneaker:',
  },
  {
    category: 'sneakers',
    id: 16,
    name: 'Air Jordan Limited',
    title: 'Air Jordan Limited',
    imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
    price: 190,
    desc: 'description of the sneaker:',
  },
  {
    category: 'sneakers',
    id: 17,
    name: 'Timberlands',
    title: 'Timberlands',
    imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
    price: 200,
    desc: 'description of the sneaker:',
  },
  {
    category: 'jackets',
    id: 18,
    name: 'Black Jean Shearling',
    title: 'Black Jean Shearling',
    imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
    price: 125,
    desc: 'description of the sneaker:',
  },
  {
    category: 'jackets',
    id: 19,
    name: 'Blue Jean Jacket',
    title: 'Blue Jean Jacket',
    imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
    price: 90,
    desc: 'description of the sneaker:',
  },
  {
    category: 'jackets',
    id: 20,
    name: 'Grey Jean Jacket',
    title: 'Grey Jean Jacket',
    imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
    price: 90,
    desc: 'description of the jacket:',
  },
  {
    category: 'jackets',
    id: 21,
    name: 'Brown Shearling',
    title: 'Brown Shearling',
    imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
    price: 165,
    desc: 'description of the jacket:',
  },
  {
    category: 'jackets',
    id: 22,
    name: 'Tan Trench',
    title: 'Tan Trench',
    imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
    price: 185,
    desc: 'description of the jacket:',
  },
  {
    category: 'woments',
    id: 23,
    name: 'Blue Tanktop',
    title: 'Blue Tanktop',
    imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
    price: 25,
    desc: 'description of the jacket:',
  },
  {
    category: 'woments',
    id: 24,
    name: 'Floral Blouse',
    title: 'Floral Blouse',
    imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
    price: 20,
    desc: 'description of the jacket:',
  },
  {
    category: 'woments',
    id: 25,
    name: 'Floral Dress',
    title: 'Floral Dress',
    imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
    price: 80,
    desc: 'description of the jacket:',
  },
  {
    category: 'woments',
    id: 26,
    name: 'Red Dots Dress',
    title: 'Red Dots Dress',
    imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
    price: 80,
    desc: 'description of the jacket:',
  },
  {
    category: 'woments',
    id: 27,
    name: 'Striped Sweater',
    title: 'Striped Sweater',
    imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
    price: 45,
    desc: 'description of the jacket:',
  },
  {
    category: 'woments',
    id: 28,
    name: 'Yellow Track Suit',
    title: 'Yellow Track Suit',
    imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
    price: 135,
    desc: 'description of the woment dress:',
  },
  {
    category: 'woments',
    id: 29,
    name: 'White Blouse',
    title: 'White Blouse',
    imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
    price: 20,
    desc: 'description of the woment dress:',
  },
  {
    category: 'mens',
    id: 30,
    name: 'Camo Down Vest',
    title: 'Camo Down Vest',
    imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
    price: 325,
    desc: 'description of the man clothes:',
  },
  {
    category: 'mens',
    id: 31,
    name: 'Floral T-shirt',
    title: 'Floral T-shirt',
    imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
    price: 20,
    desc: 'description of the man clothes:',
  },
  {
    category: 'mens',
    id: 32,
    name: 'Black & White Longsleeve',
    title: 'Black & White Longsleeve',
    imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
    price: 25,
    desc: 'description of the man clothes:',
  },
  {
    category: 'mens',
    id: 33,
    name: 'Pink T-shirt',
    title: 'Pink T-shirt',
    imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
    price: 25,
    desc: 'description of the man clothes:',
  },
  {
    category: 'mens',
    id: 34,
    name: 'Jean Long Sleeve',
    title: 'Jean Long Sleeve',
    imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
    price: 40,
    desc: 'description of the man clothes:',
  },
  {
    category: 'mens',
    id: 35,
    name: 'Burgundy T-shirt',
    title: 'Burgundy T-shirt',
    imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
    price: 25,
    desc: 'description of the man clothes:',
  },
]

import { addCollectionAndDocuments } from './util/firebase/firebase.utils';

export const createProducts = async ()=> {
  const res = await addCollectionAndDocuments("products", Product_Data);
  return res
}