# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  REACT_APP_Firebase_apiKey: ""
  REACT_APP_Firebase_authDomain: ""
  REACT_APP_Firebase_aprojectId: ""
  REACT_APP_Firebase_astorageBucket: ""
  REACT_APP_Firebase_amessagingSenderId: ""
  REACT_APP_Firebase_aappId: ""

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: CI=false yarn run build --if-present
    - run: yarn test . --coverage --reporters='html' --coverageDirectory='output/coverage/report'
